### ISSUE TITLE
how to show the candidate panel in sway(1.6)? thanks.

### ISSUE THREAD

**Issue by liangqi** [xdavidwu/wlchewing#6]
`$ sway --version`
`sway version 1.6-3bf99198 (Jun 10 2021, branch 'master')`
`wlchewing --dock=dock`

I have tried dock/yield/no, but didn't get the candidate panel shown on the screen. Could you help to guide me a bit? Thanks in advance.

For client, I used gtk3-demo->Text View->Multiple Views, the input method works fine, 1L->包.

**Comment by xdavidwu** [comment]
It works fine on my machine with the same sway commit, even if without any sway configuration.

A few things to be checked:

* Like most other libchewing input methods, the candidate panel is summoned by moving cursor to the front of the word and press down arrow button, in preedit mode (when word is not yet committed; most client indicates that with underline).
* Make sure your gtk3 is using text-input-unstable-v3 wayland protocol as input method backend, so that it won't use other backends like ibus or fcitx. This can be done by setting environment variable `GTK_IM_MODULE=wayland`.
* If it is still not working, launch wlchewing in where you can see stderr, with environment variable `WAYLAND_DEBUG=1`. This will dump wayland traffic to stderr. See if there is traffic when you type. If yes, provide the output and sway log so I can investigate. If not, your gtk3 is likely not using wlchewing.

By the way, if you want to test it with no sway configuration, launch sway with `sway -c /dev/null` and launch wlchewing and applications with `WAYLAND_DISPLAY` set to the wayland socket name (find it under `XDG_RUNTIME_DIR`).

**Comment by liangqi** [comment]
@xdavidwu , thanks a lot.

Now I mange to get the candidate panel, like "1" + "L" + Space, when "包" showing in pre-edit string, press Down, then get the candidates showing in the bottom of the screen.

**Comment by xdavidwu** [comment]
If you mean floating at exactly where the text is, with current protocols, it needs `zwp_input_popup_surface_v2` in `input-method-unstable-v2` implemented on compositor side, and code to use it in wlchewing side. On the compositor side, there are PRs for sway/wlroots, but they found current protocol restrictive. They moved to work on first improving the protocol instead and I don't think the old PRs will land, so I have no plan implementing wlchewing side code yet in short term.

Without that interface support, I used `wlr-layer-shell` instead, which basically enables us placing our window above all normal windows anywhere we want. But there is no way to know where the text input is, so currently the position can only be fixed.

BTW, if you want just something other then bottom, there are options to move it to the top.
